[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[deploy.rules]]
path = "/api/*"
type = "proxy"

[[deploy.rules]]
path = "/*"
type = "rewrite"
destination = "/index.html"

[deploy.envs]
PORT = "3000"
NODE_ENV = "production"
